name: template
description: "An application that provide a template for standard ui & ux design"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Android : Version Name               + Version Code
# iOS     : CFBundleShortVersionString + CFBundleVersion
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # Provide iOS Cupertino style icons.
  cupertino_icons: ^1.0.8

  # Provide State Management
  provider: ^6.1.2

  # Provide application information
  package_info_plus: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Provide a set of recommended lints to encourage good coding practices.
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Declare Multimedia Resources
  assets:
    - assets/images/